[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus-free-icons = { version = "0.10.0", features = ["lucide"] }
indexmap = "2.14.0"
js-sys = "0.3.103"
wasm-bindgen = "0.2.106"
web-sys = { version = "0.3.103", features = [
    "Document",
    "Element",
    "EventTarget",
    "HtmlIFrameElement",
    "Location",
    "MessageEvent",
    "Node",
    "NodeList",
    "Window",
] }

dioxus = { workspace = true, features = ["fullstack"] }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }

backend = { workspace = true }
models = { workspace = true }

# TODO: Implement MA-58
# jsonwebtoken = "10.3.0"
# axum-jwt-auth = "0.6.3"

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "backend/server"]
