[package]
name = "frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus-free-icons = { version = "0.10.0", features = ["lucide"] }
web-sys = "0.3.85"
wasm-bindgen = "0.2.108"
indexmap = "2.14.0"

dioxus = { workspace = true, features = ["fullstack"] }
serde_json = { workspace = true }
uuid = { workspace = true }

backend = { workspace = true }
models = { workspace = true }

# TODO: Implement MA-58
# jsonwebtoken = "10.3.0"
# axum-jwt-auth = "0.6.3"

[features]
default = []
web = ["dioxus/web"]
server = ["dioxus/server", "backend/server"]
