[application]
asset_dir = "www-root/assets"

[web.app]

# HTML title tag content
title = "Salus Image Viewer"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[fullstack.https]
enabled = true
mkcert = false
key_path = ".certs/key.pem"
cert_path = ".certs/cert.pem"
