[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["full"] }
axum = "0.8.8"
axum-server = { version = "0.8.0", features = ["tls-rustls"] }

dioxus = { workspace = true, features = ["fullstack"] }
serde_json = { workspace = true }

models = { workspace = true }

[features]
server = ["dioxus/server"]