[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
tower-http = { version = "0.7.0", features = ["cors"] }
tempfile = "3.27.0"
wait-timeout = { version = "0.2.1", optional = true }

dioxus = { workspace = true, features = ["fullstack"] }
serde = { workspace = true }
serde_json = { workspace = true }

models = { workspace = true }

[features]
server = ["dioxus/server", "dep:wait-timeout"]
